### ISSUE TITLE
Chrome - IME not working on Wikipedia search box

### ISSUE THREAD

**Issue by navaneeth** [varnamproject/varnam-browser-addons#1]
IME is not working on wikipedia.org search box. This is most likely because of the input field's type. It is set as 'search'.

**Comment by jijeshmohan** [comment]
In chrome browser I have tested in it is working. Please verify ( Chrome version : Version 23.0.1271.101 & Mac 10.8.2 )

![Screen Shot 2013-01-01 at 11 43 32 AM](https://f.cloud.github.com/assets/43115/37147/82f35356-53da-11e2-9d22-cc128c4870d3.png)

![Screen Shot 2013-01-01 at 11 42 17 AM](https://f.cloud.github.com/assets/43115/37148/894c9352-53da-11e2-8d29-ea144ef5cc76.png)

**Comment by navaneeth** [comment]
It works in the search box. But not in the search box in the home page. Visit www.wikipedia.org and try the search box there.

**Comment by jijeshmohan** [comment]
Looks like the problem is with jquery plugins which we are using. See the error

Error in event handler for 'undefined': Cannot read property 'start' of undefined TypeError: Cannot read property 'start' of undefined
    at getWordBeginingPosition (chrome-extension://abcfkeabpcanobhdmcmdabejaamephaf/js/varnam.js:93:36)
    at positionPopup (chrome-extension://abcfkeabpcanobhdmcmdabejaamephaf/js/varnam.js:62:19)
    at displaySugg (chrome-extension://abcfkeabpcanobhdmcmdabejaamephaf/js/varnam.js:53:13)
    at active (chrome-extension://abcfkeabpcanobhdmcmdabejaamephaf/js/varnam.js:6:13)
    at chrome.Event.dispatchToListener (event_bindings:387:21)
    at chrome.Event.dispatch_ (event_bindings:373:27)
    at chrome.Event.dispatch (event_bindings:393:17)
    at miscellaneous_bindings:165:35
    at chrome.Event.dispatchToListener (event_bindings:387:21)
    at chrome.Event.dispatch_ (event_bindings:373:27)
