### ISSUE TITLE
After installing add-on, Error Console prints errors

### ISSUE THREAD

**Issue by navaneeth** [varnamproject/varnam-browser-addons#36]
Error: y-translate: An exception occurred.
Error: The page is currently hidden and can no longer be used until it is visible again.
resource://jid1-cxafu9ddh0q8gq-at-jetpack/addon-sdk/lib/sdk/content/worker.js 404
Traceback (most recent call last):
  File "resource://jid1-cxafu9ddh0q8gq-at-jetpack/addon-sdk/lib/sdk/net/xhr.js", line 126, in
    self._orsc.apply(self, arguments);
  File "resource://jid1-cxafu9ddh0q8gq-at-jetpack/addon-sdk/lib/sdk/request.js", line 91, in onreadystatechange
    emit(target, 'complete', response);
  File "resource://jid1-cxafu9ddh0q8gq-at-jetpack/addon-sdk/lib/sdk/event/core.js", line 83, in emit
    for each (let item in emit.lazy.apply(emit.lazy, arguments)) {
  File "resource://jid1-cxafu9ddh0q8gq-at-jetpack/addon-sdk/lib/sdk/event/core.js", line 101, in lazy
    yield listeners.shift().apply(target, args);
  File "resource://jid1-cxafu9ddh0q8gq-at-jetpack/y-translate/lib/main.js", line 51, in translate.onComplete
    translated(worker, response);
  File "resource://jid1-cxafu9ddh0q8gq-at-jetpack/y-translate/lib/main.js", line 73, in translated
    worker.port.emit("showTranslated", result.source, result.trans, also, also2);
  File "resource://jid1-cxafu9ddh0q8gq-at-jetpack/addon-sdk/lib/sdk/content/worker.js", line 369, in
    emit: function () self._emitEventToContent(Array.slice(arguments))
  File "resource://jid1-cxafu9ddh0q8gq-at-jetpack/addon-sdk/lib/sdk/content/worker.js", line 404, in _emitEventToContent
    throw new Error(ERR_FROZEN);

**Comment by navaneeth** [comment]
This is fixed in ec276b96b5486057b6d1d480a506aaa993ad928d
